<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class DetailHasilPenilaianSeeder extends Seeder
{
    public function run()
    {
        $this->db->disableForeignKeyChecks();
        $this->db->table('detail_hasil_penilaian')->truncate();
        $sql = <<<'EOT'
INSERT INTO `detail_hasil_penilaian` (`id`, `hasil_supervisi_id`, `aspek_penilaian_id`, `skor`, `catatan`, `created_at`) VALUES
(195, 17, 25, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(196, 17, 26, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(197, 17, 27, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(198, 17, 28, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(199, 17, 29, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(200, 17, 30, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(201, 17, 31, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(202, 17, 32, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(203, 17, 33, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(204, 17, 34, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(205, 17, 35, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(206, 17, 36, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(207, 18, 37, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(208, 18, 38, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(209, 18, 39, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(210, 18, 40, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(211, 18, 41, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(212, 18, 42, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(213, 18, 43, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(214, 18, 44, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(215, 18, 45, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(216, 18, 46, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(217, 18, 47, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(218, 18, 48, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(339, 11, 1, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(340, 11, 2, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(341, 11, 3, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(342, 11, 4, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(343, 11, 5, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(344, 11, 6, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(345, 11, 7, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(346, 11, 8, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(347, 11, 9, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(348, 11, 10, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(349, 11, 11, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(350, 11, 12, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(351, 14, 13, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(352, 14, 14, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(353, 14, 15, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(354, 14, 16, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(355, 14, 17, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(356, 14, 18, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(357, 14, 19, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(358, 14, 20, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(359, 14, 21, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(360, 14, 22, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(361, 14, 23, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(362, 14, 24, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(363, 13, 25, 4, 'Sangat Baik.', NULL),
(364, 13, 26, 4, 'Sangat Baik.', NULL),
(365, 13, 27, 4, 'Sangat Baik.', NULL),
(366, 13, 28, 4, 'Sangat Baik.', NULL),
(367, 13, 29, 4, 'Sangat Baik.', NULL),
(368, 13, 30, 4, 'Sangat Baik.', NULL),
(369, 13, 31, 4, 'Sangat Baik.', NULL),
(370, 13, 32, 4, 'Sangat Baik.', NULL),
(371, 13, 33, 4, 'Sangat Baik.', NULL),
(372, 13, 34, 4, 'Sangat Baik.', NULL),
(373, 13, 35, 4, 'Sangat Baik.', NULL),
(374, 13, 36, 4, 'Sangat Baik.', NULL),
(375, 12, 37, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(376, 12, 38, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(377, 12, 39, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(378, 12, 40, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(379, 12, 41, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(380, 12, 42, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(381, 12, 43, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(382, 12, 44, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(383, 12, 45, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(384, 12, 46, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(385, 12, 47, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(386, 12, 48, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(435, 19, 1, 4, 'Sudah baik, pertahankan', NULL),
(436, 19, 2, 4, 'Sudah baik, pertahankan', NULL),
(437, 19, 3, 4, 'Sudah baik, pertahankan', NULL),
(438, 19, 4, 3, 'Sudah baik, pertahankan', NULL),
(439, 19, 5, 3, 'Sudah baik, pertahankan', NULL),
(440, 19, 6, 4, 'Sudah baik, pertahankan', NULL),
(441, 19, 7, 3, 'Sudah baik, pertahankan', NULL),
(442, 19, 8, 3, 'Sudah baik, pertahankan', NULL),
(443, 19, 9, 3, 'Sudah baik, pertahankan', NULL),
(444, 19, 10, 3, 'Sudah baik, pertahankan', NULL),
(445, 19, 11, 3, 'Sudah baik, pertahankan', NULL),
(446, 19, 12, 3, 'Sudah baik, pertahankan', NULL),
(447, 20, 13, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(448, 20, 14, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(449, 20, 15, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(450, 20, 16, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(451, 20, 17, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(452, 20, 18, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(453, 20, 19, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(454, 20, 20, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(455, 20, 21, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(456, 20, 22, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(457, 20, 23, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(458, 20, 24, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(459, 21, 25, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(460, 21, 26, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(461, 21, 27, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(462, 21, 28, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(463, 21, 29, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(464, 21, 30, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(465, 21, 31, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(466, 21, 32, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(467, 21, 33, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(468, 21, 34, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(469, 21, 35, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(470, 21, 36, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(471, 22, 37, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(472, 22, 38, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(473, 22, 39, 2, 'Cukup, Memiliki bukti dukung, tetapi belum lengkap.', NULL),
(474, 22, 40, 2, 'Cukup, Memiliki bukti dukung, tetapi belum lengkap.', NULL),
(475, 22, 41, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(476, 22, 42, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(477, 22, 43, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(478, 22, 44, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(479, 22, 45, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(480, 22, 46, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(481, 22, 47, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(482, 22, 48, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(483, 23, 1, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(484, 23, 2, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(485, 23, 3, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(486, 23, 4, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(487, 23, 5, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(488, 23, 6, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(489, 23, 7, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(490, 23, 8, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(491, 23, 9, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(492, 23, 10, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(493, 23, 11, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(494, 23, 12, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(495, 24, 13, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(496, 24, 14, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(497, 24, 15, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(498, 24, 16, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(499, 24, 17, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(500, 24, 18, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(501, 24, 19, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(502, 24, 20, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(503, 24, 21, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(504, 24, 22, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(505, 24, 23, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(506, 24, 24, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(507, 25, 25, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(508, 25, 26, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(509, 25, 27, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(510, 25, 28, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(511, 25, 29, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(512, 25, 30, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(513, 25, 31, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(514, 25, 32, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(515, 25, 33, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(516, 25, 34, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(517, 25, 35, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(518, 25, 36, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(519, 26, 37, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(520, 26, 38, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(521, 26, 39, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(522, 26, 40, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(523, 26, 41, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(524, 26, 42, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(525, 26, 43, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(526, 26, 44, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(527, 26, 45, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(528, 26, 46, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(529, 26, 47, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(530, 26, 48, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(531, 16, 13, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(532, 16, 14, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(533, 16, 15, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(534, 16, 16, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(535, 16, 17, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(536, 16, 18, 4, 'Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(537, 16, 19, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(538, 16, 20, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(539, 16, 21, 4, 'sepenuhnya sesuai.', NULL),
(540, 16, 22, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(541, 16, 23, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(542, 16, 24, 3, 'Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(543, 15, 1, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(544, 15, 2, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(545, 15, 3, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(546, 15, 4, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(547, 15, 5, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(548, 15, 6, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(549, 15, 7, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(550, 15, 8, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(551, 15, 9, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(552, 15, 10, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(553, 15, 11, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(554, 15, 12, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(555, 27, 1, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(556, 27, 2, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(557, 27, 3, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(558, 27, 4, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(559, 27, 5, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(560, 27, 6, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(561, 27, 7, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(562, 27, 8, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(563, 27, 9, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(564, 27, 10, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(565, 27, 11, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(566, 27, 12, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(567, 28, 37, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(568, 28, 38, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(569, 28, 39, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(570, 28, 40, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(571, 28, 41, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(572, 28, 42, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(573, 28, 43, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(574, 28, 44, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(575, 28, 45, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(576, 28, 46, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(577, 28, 47, 4, 'Sangat Baik, sebagai Wali kelas 5b.', NULL),
(578, 28, 48, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(579, 29, 13, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(580, 29, 14, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(581, 29, 15, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(582, 29, 16, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(583, 29, 17, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(584, 29, 18, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(585, 29, 19, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(586, 29, 20, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(587, 29, 21, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(588, 29, 22, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(589, 29, 23, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(590, 29, 24, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(591, 30, 25, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(592, 30, 26, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(593, 30, 27, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(594, 30, 28, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(595, 30, 29, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(596, 30, 30, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(597, 30, 31, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(598, 30, 32, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(599, 30, 33, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(600, 30, 34, 4, 'Sangat Baik,Memiliki bukti dukung yang lengkap dan sepenuhnya sesuai.', NULL),
(601, 30, 35, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL),
(602, 30, 36, 3, 'Baik, Memiliki bukti dukung yang lengkap, namun belum sepenuhnya sesuai.', NULL);
EOT;
        $this->db->query($sql);
        $this->db->enableForeignKeyChecks();
    }
}
